service: serverless-CRUD
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  createUser2:
    handler: modules/createuser.userdata
    events:
      - httpApi:
          path: /users/create
          method: post
  getAll:
    handler: modules/getAllUser.userdata
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: modules/getUser.userdata
    events:
      - httpApi:
          path:  /users/find/{email}
          method: get
  updateUser:
    handler: modules/updateuser.userdata
    events:
      - httpApi:
          path:  /users/update/{user_id}
          method: patch
  deleteUser:
    handler: modules/deleteuser.userdata
    events:
      - httpApi:
          path:  /users/delete/{user_id}
          method: delete
