service: serverless-CRUD
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  createUser2:
    handler: controller/handlers.newUser
    events:
      - httpApi:
          path: /users/create
          method: post
  getAll:
    handler: controller/handlers.allUsers
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: controller/handlers.getUser
    events:
      - httpApi:
          path:  /users/find/{email}
          method: get
  updateUser:
    handler: controller/handlers.updateData
    events:
      - httpApi:
          path:  /users/update/{user_id}
          method: patch
  deleteUser:
    handler: controller/handlers.deleteUser
    events:
      - httpApi:
          path:  /users/delete/{user_id}
          method: delete
